name: 'UC4 Dev_Network Setup'
description: 'Sets up the UC4 Dev-Network'

inputs:
  network_folder:
    description: 'path to the network where we can find the network.sh script.'
    required: true
    default: 'hlf-dev-network'

runs:
    using: "composite"
    
    steps:    
    # set up Dev_network
    - name: Set up dev_network - dockers
      run: |
        pushd ./${{ inputs.network_folder }}
        echo "##########################"
        echo "#  start network script  #"
        echo "##########################"
        ./network.sh feature/mutli_field_of_study &
        echo "##########################"
        echo "# started network script #"
        echo "##########################"
        echo "#    begin sleep         #"
        echo "##########################"
        sleep 180
        echo "#    finish sleep        #"
        echo "##########################"
        popd
      shell: bash