name: Hyperledger_Scala_With_Dev_Network

on:
  push:
    branches:
      - '**feature**'
      - '**fix**'
      - develop
      - master
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
  pull_request:
    branches: 
      - develop
      - master

jobs:

  DeployAndTestManagers:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2

    # Checks out dev network
    - name : Check out dev_network
      uses: actions/checkout@v2
      with:
        repository: 'upb-uc4/hyperledger_dev_network'
        ref: 'develop'
        path: 'hyperledger_dev_network'
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Run ManagerTests
    - name: setupAndTest
      uses: ./.github/actions/dev_network_test
      with:
        what-to-test: 'ManagerTests'

  
  DeployAndTestCourseAccess:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    # Run CourseAccessTests
    - name: setupAndTest
      uses: ./.github/actions/dev_network_test
      with:
        what-to-test: 'CourseAccessTests'

        
  DeployAndTestCourseError:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    # Run CourseErrorTests
    - name: setupAndTest
      uses: ./.github/actions/dev_network_test
      with:
        what-to-test: 'CourseErrorTests'

        
  DeployAndTestMatriculationError:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    # Run MatriculationErrorTests
    - name: setupAndTest
      uses: ./.github/actions/dev_network_test
      with:
        what-to-test: 'MatriculationErrorTests'