name: Hyperledger Scala Test Pipeline

on:
  push:
    branches:
      - '**feature**'
      - '**fix**'
      - develop
      - master
  pull_request:
    branches: 
      - develop
      - master

jobs:

  DeployAndTestConnection:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2
      
    - name: setupAndTest
      uses: upb-uc4/hyperledger_api/dev_network_setup
      with:
        what-to-test: 'ConnectionTests'