name: Hyperledger_Scala_With_Dev_Network

on:
  push:
    branches:
      - '**feature**'
      - '**fix**'
      - develop
      - master
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
  pull_request:
    branches: 
      - develop
      - master

jobs:

  DeployAndTestManagers:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2

    # Checks out dev network
    - name : Check out dev_network
      uses: actions/checkout@v2
      with:
        repository: 'upb-uc4/hyperledger_dev_network'
        ref: 'develop'
        path: 'hyperledger_dev_network'
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Setup Network
    - name: setup dev_network
      uses: ./.github/actions/dev_network_setup

    # Run Tests
    - name: runt tests with coverage and reports
      uses: ./.github/actions/test_with_coverage
      with:
        what-to-test: 'ManagerTests CourseAccessTests CourseErrorTests MatriculationErrorTests'

    # Combine reports
    - name: Scalatest multiproject HTML merger
      uses: bastihav/scalatest-multiproject-html-action@v1
      if: always()
      with:
        path: target/test_reports/

    # Upload Test Report
    - name: Upload test report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-reports
        path: target/test_reports/

    # Uplaod Coverage Report
    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: target/scala-2.13/scoverage-report