name: Hyperledger_Scala_With_Dev_Network

on:
  # daily at 00:00
  schedule:
    - cron: '0 0 * * *'
  # manual triggers with parameters
  workflow_dispatch:
    inputs:
      chaincode_target:
        description: 'Chaincode Target Branch'
        required: true
        default: 'develop'
      test_set:
        description: 'Define which tests to run'
        required: true
        default: '*ManagerTests *CourseAccessTests *CourseErrorTests *MatriculationErrorTests *MatriculationAccessTests'
  # on push event
  push:
    # except for these files
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - .github/workflows/production_network_test.yml
      - .github/workflows/style_check.yaml
  # on pull request to protected branches
  pull_request:
    branches: 
      - develop
      - master

jobs:

  DeployAndTestDevNetwork:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # ################### DEV NETWORK ############ #
    # Checks out dev network
    - name : Check out dev_network
      uses: actions/checkout@v2
      with:
        repository: 'upb-uc4/hlf-dev-network'
        ref: 'develop'
        path: 'hlf-dev-network'
    
    # Setup Network
    - name: setup dev_network
      uses: ./.github/actions/dev_network_setup
      with:
        network_folder: 'hlf-dev-network'
        chaincode_branch: '${{ github.event.inputs.chaincode_target }}'
    # ################### DEV NETWORK ############ #
    
    # ################### TEST WITH REPORTS ############# #
    # Run Tests
    - name: run tests with coverage and reports
      uses: NikoBergemann/action-sbt-test-report@v1
      with:
        what-to-test: '${{ github.event.inputs.test_set }}'

    # Combine reports
    - name: Scalatest multiproject HTML merger
      uses: bastihav/scalatest-multiproject-html-action@v1
      if: always()
      with:
        path: target/test_reports/

    # Upload Test Report
    - name: Upload test report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-reports
        path: target/test_reports/

    # Uplaod Coverage Report
    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: target/scala-2.13/scoverage-report
    # ################### TEST WITH REPORTS ############# #
