name: Hyperledger  Production Scala Test Pipeline

on:
  push:
    branches:
      - '**feature**'
      - '**fix**'
      - develop
      - master
  pull_request:
    branches: 
      - develop
      - master

jobs:

  DeployAndTestScalaAccess:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2

    - name : Check out production network
      uses: actions/checkout@v2
      with:
        repository: 'upb-uc4/hlf-network'
        ref: 'feature/update-chaincode-repository'
        path: 'hlf-network'

    - name: Check structure
      run: |
        ls
        pushd hlf-network
        ls
        popd
      shell:
        bash

      # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Set up minikube
    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Start Network
      run: |
        pushd hlf-network
        ./startNetwork.sh
        popd

    - name: Install Chaincode
      run: |
        pushd hlf-network
        ./installChaincode.sh
        popd
      shell:
        bash

    # run enrollmentTests tests
    - name: Run enrollmentTests tests
      run: |
        echo "##########################"
        echo "#    starting test       #"
        echo "##########################"
        pushd
        sbt "testOnly *EnrollmentTests"
        echo "##########################"
        echo "#    finished test       #"
        echo "##########################"
      shell:
        bash
