name: Hyperledger_Scala_With_Production_Network

on:  
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug option'
        required: false
        default: 'none'
  push:
    branches:
      - '**feature**'
      - '**fix**'
      - develop
      - master
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
  pull_request:
    branches: 
      - develop
      - master

jobs:

  DeployAndTestProductionNetwork:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2

    # Checks out production network
    - name : Check out production network
      uses: actions/checkout@v2
      with:
        repository: 'upb-uc4/hlf-network'
        ref: 'develop'
        path: 'hlf-network'

    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    # Prepare for mounts
    - name: Create folder for mounts
      run: |
        pushd hlf-network
        source ./env.sh
        sudo mkdir -p $HL_MOUNT
        sudo chmod -R 777 $K8S_MOUNT
        popd

    # Generate files
    - name: Generate files from templates
      run: |
        pushd hlf-network
        ./scripts/setMountFolder.sh
        popd

    # Start KIND
    - name: Start KinD
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: "v0.7.0"
        config: hlf-network/kind.yaml

    # Setup Network
    - name: setup production network
      uses: ./.github/actions/production_network_setup
      with:
        network_folder: 'hlf-network'

    # Run Tests
    - name: run tests with coverage and reports
      uses: ./.github/actions/test_with_coverage
      with:
        what-to-test: '*EnrollmentTests *ManagerTests *CourseAccessTests *CourseErrorTests *MatriculationErrorTests *MatriculationAccessTests'
      env:
        Target: 'ProductionNetwork'

    # Combine reports
    - name: Scalatest multiproject HTML merger
      uses: bastihav/scalatest-multiproject-html-action@v1
      if: always()
      with:
        path: target/test_reports/

    # Upload Test Report
    - name: Upload test report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-reports
        path: target/test_reports/

    # Upload Coverage Report
    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: target/scala-2.13/scoverage-report
