name: Publish to Sonatype

on:
  # on push tag
  push:
    tags: ['*']

jobs:

  PublishRelease:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out source repository
        uses: actions/checkout@v2
      # setup scala@v2
      - uses: olafurpg/setup-scala@v7
      # setup gpg plugin
      - uses: olafurpg/setup-gpg@v2

      # release action
      - name: Publish ${{ github.ref }}
        run: |
          echo "##########################"
          echo "    sonatype publishSigned"
          echo "##########################"
          sbt publishSigned
          echo "##########################"
          echo "    sonatype Prepare"
          echo "##########################"
          sbt sonatypePrepare
          echo "##########################"
          echo "    sonatype BundleUpload"
          echo "##########################"
          sbt sonatypeBundleUpload
          echo "##########################"
          echo "    sonatype Release"
          echo "##########################"
          sbt sonatypeRelease
          echo "##########################"
          echo "    finished"
          echo "##########################"
        env: # Add env variables from secrets
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PW }}
