name: Publish to Sonatype

on:
  # on new release / tag
  on:
    release:
      types: [created]

jobs:

  Publish Release:
    runs-on: ubuntu-latest

    steps:
    # publish release
    - name: perform sbt publishSigned
      env: # Add env variables from secrets
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PW }}
      run: sbt publishSigned