name: Publish with gpg plugin

on:
  # on push tag
  push:
    tags: ['*']

jobs:

  PublishGPG:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out source repository
        uses: actions/checkout@v2
      # setup scala@v2
      - uses: olafurpg/setup-scala@v7
      # setup gpg plugin
      - uses: olafurpg/setup-gpg@v2

      # release action
      - name: Publish ${{ github.ref }}
        run: |
          echo "$PGP_SECRET" | gpg --import
          echo "##########################"
          echo "    ci-release"
          echo "##########################"
          sbt ci-release
        env: # Add env variables from secrets
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PW }}
